# [distributions.foxy.env]
# ROS_VERSION = "2"
# ros_version = "2"
# ROS_PYTHON_VERSION = "3"
# ROS_DISTRO = "foxy"
# IGNITION_VERSION = "citadel"
# RMF_ENABLE_FAILOVER = "0"
# BUILD_WITH_LDMRS_SUPPORT = "0"

# [distributions.galactic.env]
# ROS_VERSION = "2"
# ros_version = "2"
# ROS_PYTHON_VERSION = "3"
# ROS_DISTRO = "galactic"
# IGNITION_VERSION = "edifice"
# RMF_ENABLE_FAILOVER = "0"

[distributions.humble.env]
ROS_VERSION = "2"
ros_version = "2"
ROS_PYTHON_VERSION = "3"
ROS_DISTRO = "humble"
IGNITION_VERSION = "fortress"
GZ_VERSION = "fortress"
RMF_ENABLE_FAILOVER = "0"
