name: cachix
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: cachix
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: ros2nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipPush: true
    - run: nix run .#ros2nix -- ci --distro=humble --buildAll --important desktop
